### ISSUE TITLE
Allow setting a caption for images in markdown

### ISSUE THREAD

**Issue by tobie** [unlockopen/www.unlockopen.com-v4#20]
Leverage `renderImage` method from [`markdown-it-eleventy-img` plugin](https://www.npmjs.com/package/markdown-it-eleventy-img#custom-image-rendering) to allow adding image captions in markdown.

```md
![alt text](url "caption")
```

Should turn into something like:

```html
<figure>
    <source>[...]</source>
    <figcaption>caption</figcaption>
</figure>
```

The output should be consistent with the shortcode image renderer and ideally leverage the same codebase.

Caption must support inline markdown.

**Comment by tobie** [comment]
OK, so apparently this short hand (`![alt text](url "caption")`) is what caused the memory issue I spent half my weekend debugging.

**Comment by tobie** [comment]
Filed #21 to handle the markdown issue first.

**Comment by madrilene** [comment]
Fixed / added in https://github.com/unlockopen/www.unlockopen.com-v4/pull/22.
