### ISSUE TITLE
Properly handle images in markdown

### ISSUE THREAD

**Issue by tobie** [unlockopen/www.unlockopen.com-v4#21]
Currently images in markdown (not using a shortcode) are breaking the build.

Is this something we can fix?

**Comment by madrilene** [comment]
[markdown config ](https://github.com/unlockopen/www.unlockopen.com-v4/blob/main/src/_eleventy/plugins/markdown.js) used a plugin so Eleventy Image could handle markdown images. Problem: The plugin has no option for captions, but adds an unnecessary `title` attr. I exchanged that module for `markdown-it-image-figures`. 

https://github.com/unlockopen/www.unlockopen.com-v4/pull/22

**Comment by madrilene** [comment]
Fixed in https://github.com/unlockopen/www.unlockopen.com-v4/pull/25
