### ISSUE TITLE
Mobile Menu Behavior: Wrap Pills vs. Drawer Menu

### ISSUE THREAD

**Issue by madrilene** [unlockopen/www.unlockopen.com-v4#31]
### Overview
Decide on the approach for mobile menu behavior: whether to use wrap pills or implement a drawer menu. 

### Task
- [ ] Discuss and decide on the preferred method for mobile menu.
- [ ] Draft a preliminary design for approval before implementation.

**Comment by madrilene** [comment]
# Options
## Wrap Pills
**Pros** 
- straightforward and minimalistic approach 
- enhancing user experience by keeping all options visible 
- no extra action like tapping burger menu button needed to switch pages
- no JS dependency

**Cons**
- limits the number of items we can effectively display (should fit in one line)
- Less control over layout: Even though we limit the items, the last one may still fall to the next line on some devices


![Screenshot from 2024-05-23 14-52-51](https://github.com/unlockopen/www.unlockopen.com-v4/assets/62096871/2b0749e9-a3ca-4fbc-84e2-05792e094eb7)  ![Screenshot from 2024-05-23 14-53-31](https://github.com/unlockopen/www.unlockopen.com-v4/assets/62096871/aa301013-b0d8-42bd-b78f-6991c9c0d3c9 'caption')


##  Drawer Menu
**Pros** 
- Provides a more scalable solution for navigation with various items and subitems, keeping the mobile interface clean. 

**Cons**
- requires JS for accessibility (This is already developed and must only be activated: https://github.com/unlockopen/www.unlockopen.com-v4/blob/main/src/assets/scripts/nav-drawer.js)
- Adds the extra step op opening the navigation drawer when switching pages

![Screenshot from 2024-05-23 14-54-18](https://github.com/unlockopen/www.unlockopen.com-v4/assets/62096871/dec39344-d443-48e1-992f-015ccbca7571) ![Screenshot from 2024-05-23 14-54-25](https://github.com/unlockopen/www.unlockopen.com-v4/assets/62096871/4b2ea944-ddd7-43c2-95bf-0a4850637cce)

**Comment by tobie** [comment]
Let's go with the drawer menu.

**Comment by madrilene** [comment]
Built a drawer menu. 
Let me know if the styling works for you, and if not, what you would want to change / link to an example you like.

**Comment by tobie** [comment]
Looks good to me.

you’d want to figure out how to make scrolling scroll the menu, not the background on ios before landing, though. I remember seeing write ups about how to do this.

**Comment by madrilene** [comment]
Not sure I understand. Can you explain again? Is this an issue already? Can you tell me your iOS version so I can emulate this?

**Comment by tobie** [comment]
https://share.icloud.com/photos/030sIrH5jS_3V2uyp7sbopLmA

**Comment by tobie** [comment]
Maybe this: https://developer.chrome.com/blog/overscroll-behavior ?

**Comment by madrilene** [comment]
Ah, I see what you mean now. I'm on it.
