### ISSUE TITLE
Move article excerpts out of the YAML

### ISSUE THREAD

**Issue by tobie** [unlockopen/www.unlockopen.com-v4#4]
Could we move the article excerpts to the main body rather than as part of the YAML? See https://www.11ty.dev/docs/data-frontmatter-customize/#changing-where-your-excerpt-is-stored.

I like treating that excerpt differently visually in the article itself, but could we maybe just use CSS for that?

**Comment by madrilene** [comment]
If I understand the docs correctly, this always shows the excerpt as part of the content

> The unique feature of this configuration is that you can keep your excerpt right at the beginning of your content. You can add a delimiter where you want the excerpt to end and the rest of the content to begin. If you want the excerpt to be separate from the content, make a new key for this and store it separately in your front matter or a data file.

You may not always want the excerpt to be identical to the beginning of your article. How do you want to handle this? Add a front matter key in case your excerpt differs from the beginning of the article?

**Comment by tobie** [comment]
I'm totally fine with the excerpt always being the beginning of the content for now.

**Comment by madrilene** [comment]
Any syntax preference for the separator? Default is `---`

**Comment by tobie** [comment]
that works

**Comment by madrilene** [comment]
fixed in https://github.com/unlockopen/www.unlockopen.com-v4/commit/69dcc055ae3c4b9a6b56e743a035946559c95123
